image: Visual Studio 2017

shallow_clone: true

platform:
  - x64
  - Win32

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

only_commits:
  files:
    - src/
    - vc14/
    - .appveyor.yml
    - cmake/

install:
  - cmd : vcpkg install boost-iostreams:x64-windows
  - cmd : vcpkg install boost-asio:x64-windows
  - cmd : vcpkg install boost-system:x64-windows
  - cmd : vcpkg install boost-filesystem:x64-windows
  - cmd : vcpkg install boost-variant:x64-windows
  - cmd : vcpkg install boost-lockfree:x64-windows
  - cmd : vcpkg install cryptopp:x64-windows
  - cmd : vcpkg install luajit:x64-windows
  - cmd : vcpkg install libmariadb:x64-windows
  - cmd : vcpkg install pugixml:x64-windows
  - cmd : vcpkg install mpir:x64-windows
  - cmd : vcpkg install boost-iostreams
  - cmd : vcpkg install boost-asio
  - cmd : vcpkg install boost-system
  - cmd : vcpkg install boost-filesystem
  - cmd : vcpkg install boost-variant
  - cmd : vcpkg install boost-lockfree
  - cmd : vcpkg install cryptopp
  - cmd : vcpkg install luajit
  - cmd : vcpkg install libmariadb
  - cmd : vcpkg install pugixml
  - cmd : vcpkg install mpir

build:
  parallel: true
  # MSBuild verbosity level
  #verbosity: detailed

cache:
  - c:\tools\vcpkg\installed\

artifacts:
  - path: vc14\**\theforgottenserver*.exe
  - path: vc14\**\*.dll
