dist: bionic
language: cpp
os: linux
jobs:
  include:
    - dist: bionic
      env:
        - BUILD_TYPE=Debug LUAJIT=OFF

    - dist: bionic
      env:
        - BUILD_TYPE=Debug LUAJIT=ON

    - dist: bionic
      env:
        - BUILD_TYPE=Release LUAJIT=OFF

    - dist: bionic
      env:
        - BUILD_TYPE=Release LUAJIT=ON

    - dist: xenial
      env:
        - BUILD_TYPE=Debug LUAJIT=OFF

    - dist: xenial
      env:
        - BUILD_TYPE=Debug LUAJIT=ON

    - dist: xenial
      env:
        - BUILD_TYPE=Release LUAJIT=OFF

    - dist: xenial
      env:
        - BUILD_TYPE=Release LUAJIT=ON



compiler:
  - gcc
  # - clang


cache: apt
addons:
  apt:
    update: true
    packages:
      - libboost-date-time-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-iostreams-dev
      - libcrypto++-dev
      - liblua5.2-dev
      - libluajit-5.1-dev
      - libmysqlclient-dev
      - libpugixml-dev
      - ccache

before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DUSE_LUAJIT=${LUAJIT} ..

script: make -j`nproc`
