dist: bionic
language: cpp


matrix:
  include:
  - #dist: bionic
    compiler: gcc
    os: linux
    sudo: required
  - #dist: bionic
    compiler: clang
    os: linux
    sudo: required
  - dist: xenial
    compiler: gcc
    os: linux
    sudo: required
  - dist: xenial
    compiler: clang
    os: linux
    sudo: required

compiler:
  - clang
  - gcc
env:
  matrix:
    - BUILD_TYPE=Debug LUAJIT=OFF
    - BUILD_TYPE=Debug LUAJIT=ON
    - BUILD_TYPE=Release LUAJIT=OFF
    - BUILD_TYPE=Release LUAJIT=ON
cache: apt
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-iostreams-dev
      - libcrypto++-dev
      - liblua5.2-dev
      - libluajit-5.1-dev
      - libmysqlclient-dev
      - libpugixml-dev
      - libgmp3-dev
      - libspdlog-dev

before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DUSE_LUAJIT=${LUAJIT} ..

script: make -j`nproc`
