blank_issues_enabled: false
contact_links:
  - name: 'Help / Support'
    url: 'https://discord.gg/3NxYnyV?utm_source=Github'
    about: If you have support question or need help, please use our Discord Server.
