version: "3.3"

services:
  otserver:
    container_name: otserver
    image: midukan/endless_server
    entrypoint: /opt/otserver/otbr
    ports:
      - "7171:7171"
      - "7172:7172"
    volumes:
      - ../:/otserver
    depends_on:
      - otdb
      - otweb
      - otlogin

  otdb:
    container_name: otdb
    image: midukan/docker_otdb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=otserver
      - MYSQL_USER=otserver
      - MYSQL_PASSWORD=otserver
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

  otweb:
    container_name: otwebsite
    image: webdevops/php-nginx:alpine-php7
    restart: unless-stopped
    environment:
      - WEB_DOCUMENT_ROOT=/tmp/web/
      - WEB_DOCUMENT_INDEX=index.php
    ports:
      - "80:80"
    volumes:
      - ./data/web:/tmp/web
      - ../:/tmp/otserver/
    depends_on:
      - otdb

  otlogin:
    container_name: otwebsite_login
    image: midukan/docker_otlogin
    command: python ./login.py
    restart: unless-stopped
    volumes:
      - ./data/:/tmp/
    ports:
      - "8080:80"
    depends_on:
      - otdb

volumes:
  db-volume:
