name: Build on Windows

on:
  push:
    branches:
      - master
      - develop
      - v*

    tags:
      - v*

  pull_request:
    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt
      - .github/**

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        buildtype: [Debug, Release]
        include:
          - os: windows-latest
            triplet: x64-windows
            packages: >
              boost-asio boost-iostreams boost-system boost-filesystem
              boost-variant boost-lockfree cryptopp curl jsoncpp
              luajit libmariadb pugixml spdlog

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: Windows - remove C:/mysql*
        run: rm -r -fo C:/mysql-5.7.21-winx64
        if: contains( matrix.os, 'windows')

      # - name: Restore artifacts, or setup vcpkg (do not install any package)
      #   uses: lukka/run-vcpkg@v7
      #   id: runvcpkg
      #   with:
      #     setupOnly: true
      #     vcpkgDirectory: '${{ github.workspace }}/vcpkg'
      #     appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
      #     vcpkgTriplet: ${{ matrix.triplet }}
      #     additionalCachedPaths: ${{ github.workspace }}/build/vcpkg_installed
      #     vcpkgGitCommitId: 030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v5
        with:
          vcpkgArguments: ${{ matrix.packages }}
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgTriplet: ${{ matrix.triplet }}
          vcpkgGitCommitId: 7db401cb1ef1fc559ec9f9ce814d064c328fd767

      - name: Run CMake to install the dependencies specified in the vcpkg.json manifest, generate project file and build the project
        uses: lukka/run-cmake@v3
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          buildDirectory: ${{ github.workspace }}/build
          useVcpkgToolchainFile: true
          buildWithCMake: true

      - name: Create datapack
        if: ${{ matrix.buildtype == 'Release' }}
        shell: powershell
        run: |
          md ${{ runner.workspace }}\otservbr-global\otservbr-global
          Copy-Item ${{ runner.workspace }}\otservbr-global\config.lua.dist     ${{ runner.workspace }}\otservbr-global\otservbr-global
          Copy-Item ${{ runner.workspace }}\otservbr-global\key.pem             ${{ runner.workspace }}\otservbr-global\otservbr-global
          Copy-Item ${{ runner.workspace }}\otservbr-global\LICENSE             ${{ runner.workspace }}\otservbr-global\otservbr-global
          Copy-Item ${{ runner.workspace }}\otservbr-global\README.md           ${{ runner.workspace }}\otservbr-global\otservbr-global
          Copy-Item ${{ github.workspace }}\build\bin\otbr.exe                  ${{ runner.workspace }}\otservbr-global\otservbr-global\otbr.exe
          get-childitem -path ${{ runner.workspace }}\build -filter *.dll -recurse | copy-item -destination ${{ runner.workspace }}\otservbr-global\otservbr-global
          Copy-Item ${{ runner.workspace }}\otservbr-global\data -Destination   ${{ runner.workspace }}\otservbr-global\otservbr-global\data
          Copy-Item -Path ${{ runner.workspace }}\otservbr-global\data\* -Destination ${{ runner.workspace }}\otservbr-global\otservbr-global\data -Recurse
          Compress-Archive -Path ${{ runner.workspace }}\otservbr-global\otservbr-global -DestinationPath ${{ runner.workspace }}\otservbr.zip

      - name: Upload datapack
        if: ${{ matrix.buildtype == 'Release' }}
        uses: actions/upload-artifact@v2
        with:
          name: otbr-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: ${{ runner.workspace }}/otservbr.zip
