name: Lua syntax check

on:
  push:
    branches:
      - master
      - develop
      - v*

    tags:
      - v*

    paths:
      - data/**.lua
      - .github/**

  pull_request:
    paths:
      - data/**.lua
      - .github/**

jobs:
  luac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v5

      - name: Test Lua syntax
        run: find data/ -name '*.lua' -print0 | xargs -0 -n1 luac -p
