name: XML syntax check

on:
  push:
    branches:
      - master
      - develop
      - v*

    tags:
      - v*

    paths:
      - data/**.xml
      - .github/**

  pull_request:
    paths:
      - data/**.xml
      - .github/**

jobs:
  xmllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Test XML syntax
        run: find data/ -name '*.xml' -print0 | xargs -0 -n1 xmllint --noout
